### ISSUE TITLE
Welcome Page/layout Idea

### ISSUE THREAD

**Issue by monicafletcher** [juli1/citiparks#4]
Suggested welcome page, attached. When the button is clicked, the person is taken to a page where he can toggle between a list view and a map view (similar to how Zillow and Yelp provide in formation).

![image](https://cloud.githubusercontent.com/assets/11135852/6314777/2ab92308-b9ba-11e4-8509-df8d1e473493.png)

**Comment by juli1** [comment]
Cannot implement that in the required time. Plus, the senior is red not blue.

**Comment by juli1** [comment]
Can implement something where it will return a list. Would that fix the issue?

**Comment by monicafletcher** [comment]
Good step, I think.

**Comment by juli1** [comment]
Fixed.
