### ISSUE TITLE
Title Change

### ISSUE THREAD

**Issue by monicafletcher** [juli1/citiparks#6]
Change title from Cityparks to Citiparks on Home, List, Search, and Favorites pages (Map page is good).
Example:
![image](https://cloud.githubusercontent.com/assets/11135852/6314892/f61d9ce2-b9bd-11e4-9b05-9d5006982c58.png)

**Comment by juli1** [comment]
Do not understand the issue. Can you highlight where is the real issue and the proposed solution?

**Comment by monicafletcher** [comment]
See highlights. The name Cityparks appears on each title of the highlighted pages 
![image](https://cloud.githubusercontent.com/assets/11135852/6315036/57ad49e0-b9c2-11e4-83df-60a257f6a6b2.png)

**Comment by juli1** [comment]
fixed
